# Generated by Django 5.2.1 on 2025-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadomodel',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
